### ISSUE TITLE
0 set for Model ID

### ISSUE THREAD

**Issue by ztnel** [ztnel/myosin#54]
If a `StateModel` is initialized with an id of 0 it will trip the id check in the `__init__`

```python
if not _id:
    _id = str(uuid.uuid4())
```

This is unintended behaviour. Instead the conditional should check if the value is `None`

**Comment by Vinitvh** [comment]
Hi, I would like to fix this.

**Comment by ztnel** [comment]
Great! If you can open a pull request with that fix we can get that merged in.
